server:
  port: 8081
  tomcat:
      uri-encoding: UTF-8
      #最大工作线程数，默认200, 4核8g内存，线程数经验值800
      #操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。
      max-threads: 1000
      # 等待队列长度，默认100
      accept-count: 1000
      max-connections: 20000
      # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
      min-spare-threads: 100

#微信开放平台配置
wxopen:
  appid: wx719c937ea903be65
  appsecret: b22eabdd155cd8174e2791c95d513a7e
  ##重定向url
  ##test16web.tunnel.qydev.com 域名地址要和在微信端 回调域名配置 地址一直，否则会报回调地址参数错误
  ##http://test16web.tunnel.qydev.com 映射 127.0.0.1:8080,所以可以回调下面接口
  redirect_url: http://abcdef.vaiwan.com//api/v1/wechat/user/code

spring:
  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  logging:
    level:
      com.kalvin.kvf: error

  # druid数据源配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:10086/kvf_admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      url: jdbc:mysql://10.120.1.42:33060/kvf_admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: nhga
      password: 0573@nhga
      filters: stat,wall,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # 设置ip白名单
        allow: 127.0.0.1
        # 设置ip黑名单，优先级高于白名单
        deny:
        # 设置控制台管理用户
        #        login-username: root
        #        login-password: root
        # 是否可以重置数据
        reset-enable: false
        # 开启druid监控页面
        enabled: true

  # 静态资料访问方式
  mvc:
    static-path-pattern: /static/**

  # thymeleaf 模块配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    # 关闭页面缓存
    cache: false
    servlet:
      content-type: text/html

  # redis配置
  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # 集群配置(多个节点使用英文逗号分隔)
    #    cluster:
    #      nodes: 192.168.1.183:9001,192.168.1.183:9002


# mybatis-plus 配置
mybatis-plus:
  check-config-location: false
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kalvin.kvf.entity.*
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true


# kvf自定义配置
kvf:
  # 登录验证码是否开启
  login:
    authcode:
      enable: false
  # quartz开关
  quartz:
    enable: false
  # 缓存开关
  cache:
    enable: false